<?php

namespace ShopBundle\Repository;


/**
 * LivreurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LivreurRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByDisponibilte()
    {
        $q = $this->getEntityManager()->createQuery("select v from ShopBundle:Livreur v  where 
              v.disponibilite LIKE :oui  ")->setParameter('oui', 'oui');
        return $q->getResult();
    }

    public function findById($id)
    {
        $q = $this->getEntityManager()->createQuery("select v from ShopBundle:Livreur v  where 
              v.id LIKE :oui  ")->setParameter('oui', $id);
        return $q->getResult();
    }
}
