<?php

namespace ShopBundle\Repository;

/**
 * ProduitRatingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitRatingRepository extends \Doctrine\ORM\EntityRepository
{
}
