<?php

namespace ReparationBundle\Repository;

/**
 * ReparateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReparateurRepository extends \Doctrine\ORM\EntityRepository
{
}
