<?php

namespace ReparationBundle\Repository;

/**
 * VeloAReparerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VeloAReparerRepository extends \Doctrine\ORM\EntityRepository
{
}
