event_event:
    resource: "@EventBundle/Controller/EventController.php"
    type:     annotation

catalogue_rate:
    resource: "@CatalogueBundle/Controller/RateController.php"
    type:     annotation

catalogue_promo:
    resource: "@CatalogueBundle/Controller/PromoController.php"
    type:     annotation

catalogue_produit:
    resource: "@CatalogueBundle/Controller/ProduitController.php"
    type:     annotation

catalogue_categorie:
    resource: "@CatalogueBundle/Controller/CategorieController.php"
    type:     annotation

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /user

main:
    resource: "@MainBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

article:
    resource: "@ArticleBundle/Resources/config/routing.yml"
    prefix:   /

reparation:
    resource: "@ReparationBundle/Resources/config/routing.yml"
    prefix:   /


location:
    resource: "@LocationBundle/Resources/config/routing.yml"
    prefix:   /

shop:
    resource: "@ShopBundle/Resources/config/routing.yml"
    prefix:   /


fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"


mgilet_notification:
    resource: "@MgiletNotificationBundle/Controller/"
    prefix: /notifications