<?php

namespace MainBundle\Repository;

/**
 * VeloALouerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VeloALouerRepository extends \Doctrine\ORM\EntityRepository
{
}
