<?php

namespace EventBundle\Repository;

/**
 * ReservationeventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationeventRepository extends \Doctrine\ORM\EntityRepository
{
    public function myfindMe($user, $event)
    {
        $dql = $this
            ->getEntityManager()
            ->createQuery('SELECT R FROM EventBundle:Reservationevent R WHERE R.event = :event AND R.user = :user');
        $dql->setParameter(':event',$event)
            ->setParameter(':user', $user);
        return $dql->getResult();
    }

    public function getAllMyEvents($user)
    {
        $query  = $this->getEntityManager()->createQuery('SELECT R.event FROM EventBundle:Reservationevent R WHERE R.user = :user');
        $query->setParameter('user', $user);
        return $query->getResult();
        //$query = $this->getEntityManager()->createQuery()
    }





}
