<?php

namespace EventBundle\Repository;

/**
 * ReservationeventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationeventRepository extends \Doctrine\ORM\EntityRepository
{
}
