<?php

namespace LocationBundle\Repository;

/**
 * VeloRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VeloRepository extends \Doctrine\ORM\EntityRepository
{
    public function findEntitiesByString($str){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT v
                FROM LocationBundle:Velo v
                WHERE v.marque LIKE :str'
            )
            ->setParameter('str', '%'.$str.'%')
            ->getResult();
    }
    public function confirmedVelo(){
        return $this->getEntityManager()->createQuery(
            'SELECT v FROM LocationBundle:Velo v where v.etat=0'
        )->getResult();
    }
}
