<?php

namespace ArticleBundle\Repository;

use Doctrine\ORM\EntityRepository;
use \Doctrine\ORM\Query;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{

    public function findEntitiesByString($str){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p
                FROM ArticleBundle:Article p
                WHERE p.titre LIKE :str'
            )
            ->setParameter('str', '%'.$str.'%')
            ->getResult();
    }
    public function confirmedArticle(){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p FROM ArticleBundle:Article p where p.etat = 0'
            )
            ->getResult();
    }
    public function findArticleByid($id)
    {

        return $this->getEntityManager()
            ->createQuery(
                "SELECT a
                FROM ArticleBundle:Article
                a WHERE a.id =:id"
            )
            ->setParameter('id', $id)
            ->getOneOrNullResult();


    }
}
