facture_index:
    path:     /
    defaults: { _controller: "ReparationBundle:Facture:index" }
    methods:  GET

facture_show:
    path:     /{id}/show
    defaults: { _controller: "ReparationBundle:Facture:show" }
    methods:  GET

facture_new:
    path:     /new
    defaults: { _controller: "ReparationBundle:Facture:new" }
    methods:  [GET, POST]

facture_edit:
    path:     /{id}/edit
    defaults: { _controller: "ReparationBundle:Facture:edit" }
    methods:  [GET, POST]

facture_delete:
    path:     /{id}/delete
    defaults: { _controller: "ReparationBundle:Facture:delete" }
    methods:  DELETE
facture_pdf:
    path:     /pdf/{id}
    defaults: { _controller: "ReparationBundle:Facture:pdf" }

facture_check:
    path:     /{id}/check
    defaults: { _controller: "ReparationBundle:Facture:check" }
    methods:  GET
